{"variants":[{"paths":["\/documentation\/asyncobjects\/continuable\/resume(with:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resume","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Success"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Failure"},{"kind":"text","text":">)"}],"role":"symbol","required":true,"externalID":"s:12AsyncObjects11ContinuableP6resume4withys6ResultOy7SuccessQz7FailureQzG_tF","modules":[{"name":"AsyncObjects"}],"title":"resume(with:)"},"hierarchy":{"paths":[["doc:\/\/AsyncObjects\/documentation\/AsyncObjects","doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Continuable"]]},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Continuable\/resume(with:)"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resume"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"result"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier","text":"Result"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Success"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Failure"},{"kind":"text","text":">)"}],"platforms":["Linux"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"result","content":[{"inlineContent":[{"text":"A value to either return or throw from the continuation.","type":"text"}],"type":"paragraph"}]}]}],"abstract":[{"text":"Resume the task awaiting the continuation by having it either return normally","type":"text"},{"text":" ","type":"text"},{"text":"or throw an error based on the state of the given ","type":"text"},{"type":"codeVoice","code":"Result"},{"text":" value.","type":"text"}],"references":{"doc://AsyncObjects/documentation/AsyncObjects":{"title":"AsyncObjects","kind":"symbol","role":"collection","type":"topic","abstract":[{"type":"text","text":"Several synchronization primitives and task synchronization mechanisms introduced to aid in modern swift concurrency."}],"url":"\/documentation\/asyncobjects","identifier":"doc:\/\/AsyncObjects\/documentation\/AsyncObjects"},"doc://AsyncObjects/documentation/AsyncObjects/Continuable":{"title":"Continuable","kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A type that allows to interface between synchronous and asynchronous code,"},{"type":"text","text":" "},{"type":"text","text":"by representing task state and allowing task resuming with some value or error."}],"navigatorTitle":[{"text":"Continuable","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Continuable","kind":"identifier"}],"url":"\/documentation\/asyncobjects\/continuable","identifier":"doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Continuable"},"doc://AsyncObjects/documentation/AsyncObjects/Continuable/resume(with:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resume"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Success"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Failure"},{"kind":"text","text":">)"}],"role":"symbol","url":"\/documentation\/asyncobjects\/continuable\/resume(with:)","type":"topic","kind":"symbol","identifier":"doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Continuable\/resume(with:)","title":"resume(with:)","abstract":[{"text":"Resume the task awaiting the continuation by having it either return normally","type":"text"},{"text":" ","type":"text"},{"text":"or throw an error based on the state of the given ","type":"text"},{"type":"codeVoice","code":"Result"},{"text":" value.","type":"text"}],"required":true}}}