{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"associatedtype"},{"kind":"text","text":" "},{"kind":"identifier","text":"Failure"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/asyncobjects\/continuable\/failure"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Continuable\/Failure","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The type of error to resume the continuation with in case of failure."}],"kind":"symbol","metadata":{"role":"symbol","title":"Failure","roleHeading":"Associated Type","fragments":[{"kind":"keyword","text":"associatedtype"},{"kind":"text","text":" "},{"kind":"identifier","text":"Failure"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"symbolKind":"associatedtype","externalID":"s:12AsyncObjects11ContinuableP7FailureQa","required":true,"modules":[{"name":"AsyncObjects"}]},"hierarchy":{"paths":[["doc:\/\/AsyncObjects\/documentation\/AsyncObjects","doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Continuable"]]},"references":{"doc://AsyncObjects/documentation/AsyncObjects/Continuable/Failure":{"role":"symbol","title":"Failure","fragments":[{"kind":"keyword","text":"associatedtype"},{"kind":"text","text":" "},{"kind":"identifier","text":"Failure"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"abstract":[{"type":"text","text":"The type of error to resume the continuation with in case of failure."}],"identifier":"doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Continuable\/Failure","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/asyncobjects\/continuable\/failure"},"doc://AsyncObjects/documentation/AsyncObjects":{"role":"collection","title":"AsyncObjects","abstract":[{"type":"text","text":"Several synchronization primitives and task synchronization mechanisms introduced to aid in modern swift concurrency."}],"identifier":"doc:\/\/AsyncObjects\/documentation\/AsyncObjects","kind":"symbol","type":"topic","url":"\/documentation\/asyncobjects"},"doc://AsyncObjects/documentation/AsyncObjects/Continuable":{"role":"symbol","title":"Continuable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Continuable"}],"abstract":[{"type":"text","text":"A type that allows to interface between synchronous and asynchronous code,"},{"type":"text","text":" "},{"type":"text","text":"by representing task state and allowing task resuming with some value or error."}],"identifier":"doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Continuable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Continuable"}],"url":"\/documentation\/asyncobjects\/continuable"}}}