{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resume"},{"kind":"text","text":"() "},{"kind":"keyword","text":"where"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Success"},{"kind":"text","text":" == ()"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A continuation must be resumed at least once."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"After calling this method, control immediately returns to the caller."},{"type":"text","text":" "},{"type":"text","text":"The task continues executing when its executor schedules it."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/asyncobjects\/continuable\/resume()"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Continuable\/resume()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Resume the task that’s awaiting the continuation by returning."}],"kind":"symbol","metadata":{"role":"symbol","title":"resume()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resume"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"s:12AsyncObjects11ContinuablePAAE6resumeyyyt7SuccessRtzrlF","extendedModule":"AsyncObjects","modules":[{"name":"AsyncObjects"}]},"hierarchy":{"paths":[["doc:\/\/AsyncObjects\/documentation\/AsyncObjects","doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Continuable"]]},"references":{"doc://AsyncObjects/documentation/AsyncObjects/Continuable":{"role":"symbol","title":"Continuable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Continuable"}],"abstract":[{"type":"text","text":"A type that allows to interface between synchronous and asynchronous code,"},{"type":"text","text":" "},{"type":"text","text":"by representing task state and allowing task resuming with some value or error."}],"identifier":"doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Continuable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Continuable"}],"url":"\/documentation\/asyncobjects\/continuable"},"doc://AsyncObjects/documentation/AsyncObjects":{"role":"collection","title":"AsyncObjects","abstract":[{"type":"text","text":"Several synchronization primitives and task synchronization mechanisms introduced to aid in modern swift concurrency."}],"identifier":"doc:\/\/AsyncObjects\/documentation\/AsyncObjects","kind":"symbol","type":"topic","url":"\/documentation\/asyncobjects"},"doc://AsyncObjects/documentation/AsyncObjects/Continuable/resume()":{"role":"symbol","title":"resume()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resume"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Resume the task that’s awaiting the continuation by returning."}],"identifier":"doc:\/\/AsyncObjects\/documentation\/AsyncObjects\/Continuable\/resume()","kind":"symbol","type":"topic","url":"\/documentation\/asyncobjects\/continuable\/resume()"}}}